INSERT INTO CUSTOMERLDC VALUES ('Sandeep', 24);
INSERT INTO CUSTOMERLDC VALUES ('Hemendra', 23);
INSERT INTO CUSTOMERLDC VALUES ('Animesh', 28);
INSERT INTO CUSTOMERLDC VALUES ('SB', 25);
INSERT INTO CUSTOMERLDC VALUES ('Indranil', 30);
INSERT INTO CUSTOMERLDC VALUES ('Indranil', 30);
